name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  docs:
    uses: ./.github/workflows/_docs.yml
    permissions:
      contents: write

  release:
    needs: [docs]
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/_release.yml
    permissions:
      contents: write
